services:
  - type: web
    name: arhont-vkl
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: arhont-postgres
          property: connectionString

databases:
  - name: arhont-postgres
    databaseName: arhont_vkl
    user: arhont
    plan: free
    ipAllowList: []